name: donerf
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.8
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - pip
  - pip:
    - opencv-python
    - imageio
    - imageio-ffmpeg
    - configargparse
    - pillow
    - pyrtools
    - ptflops
    - pyquaternion
    - trimesh
    - open3d
    - transforms3d
